# Generated by Django 5.2.6 on 2025-11-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_momo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momo',
            old_name='Category',
            new_name='category',
        ),
    ]
